#!/bin/bash

REQUIRED_TOOLS=(
  npm
  git
)

for TOOL in "${REQUIRED_TOOLS[@]}"; do
  if ! command -v "${TOOL}" >/dev/null; then
    echo "${TOOL} is required... "
    exit 1
  fi
done

RELEASE=${1:-patch}
npm version "${RELEASE}"
VERSION_SEM=$(node -p "require('./package').version")
NAME=$(node -p "require('./package').name")
git add package*
git commit -m "chore(release): release ${NAME}@${VERSION_SEM}"
git tag "${NAME}@${VERSION_SEM}"
npm publish
git push origin --tags
